version: '3.9'
services:
  main:
    build: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - database

  database:
    image: mysql:5.6
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    expose:
      - "3306"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: 'on-failure'